version: "3.8"

services:
  apis:
    container_name: wealthcare-ai-gateway
    environment:
      - STAGE=local
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - 9999:9999
    restart: on-failure
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
      - ~/logs/go-docker:/app/logs
    networks:
      - wealthcareainetwork
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wealthcaredb
      - DATABASE_HOST=localhost
    image: postgres:latest
    networks:
      - wealthcareainetwork
    hostname: localhost
    ports:
      - 5431:5432
    volumes:
      - postgres-volume:/data

  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:1.104.1
    ports:
      - 5678:5678
    networks:
      - wealthcareainetwork
    volumes:
      - n8n_data:/home/node/.n8n

  fi-mcp-dev:
    container_name: fi-mcp-dev
    build:
      context: ./fi-mcp/fi-mcp-dev/
      dockerfile: dockerfile
    ports:
      - 1221:8080
    networks:
      - wealthcareainetwork

volumes:
  postgres-volume:
    driver: local
  n8n_data:
    driver: local

networks:
  wealthcareainetwork:
