FROM golang:1.23.5-alpine AS builder

# Set working directory
WORKDIR /app

# Install git (needed for go mod download)
RUN apk add --no-cache git

# Copy go mod files
COPY go.mod go.sum ./

COPY static ./static
COPY test_data_dir ./test_data_dir

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Final stage
FROM alpine:latest

# Install ca-certificates for HTTPS requests
RUN apk --no-cache add ca-certificates tzdata

# Set working directory
WORKDIR /root/

# Copy the binary from builder stage
COPY --from=builder /app/main .

COPY --from=builder /app/static ./static

COPY --from=builder /app/test_data_dir ./test_data_dir

# Expose port
EXPOSE 8080

EXPOSE 1221

# Set environment variables
ENV PORT=8080

# Command to run the application
CMD ["./main"]

